// ==========================================
// CHAMPIONS ITEMS DICTIONARY (EXPANDED)
// ==========================================

window.ItemDex = {
    // --- CHOICE ITEMS ---
    'choice-band': { physicalAttackMult: 1.5, isChoice: true },
    'choice-specs': { specialAttackMult: 1.5, isChoice: true },
    'choice-scarf': { speedMult: 1.5, isChoice: true },

    // --- ORBS & PASSIVE DAMAGE ---
    'life-orb': { bpMult: 1.3, recoilFraction: 0.1 },
    'flame-orb': { inflictsStatus: 'burn', endOfTurn: true },
    'toxic-orb': { inflictsStatus: 'bad-poison', endOfTurn: true },
    'black-sludge': { healFractionIfPoisonType: 0.0625, damageFractionIfNot: 0.125 },
    'sticky-barb': { damageFraction: 0.125, transfersOnContact: true },

    // --- DEFENSIVE & UTILITY STAPLES ---
    'eviolite': { physicalDefenseMult: 1.5, specialDefenseMult: 1.5, requiresNfe: true },
    'assault-vest': { specialDefenseMult: 1.5, restrictsStatusMoves: true },
    'heavy-duty-boots': { immuneToHazards: true },
    'rocky-helmet': { contactDamageFraction: 0.166 }, // 1/6 max HP
    'focus-sash': { survivesAtOneHp: true, consumesOnUse: true },
    'focus-band': { survivesAtOneHpChance: 10 },
    'air-balloon': { immuneToType: 'ground', popsOnHit: true },
    'leftovers': { healFraction: 0.0625 }, // 1/16 max HP
    'shell-bell': { healsDamageDealtFraction: 0.125 },

    // --- SPECIES SPECIFIC ---
    'light-ball': { physicalAttackMult: 2.0, specialAttackMult: 2.0, speciesRequirement: 'pikachu' },
    'thick-club': { physicalAttackMult: 2.0, speciesRequirement: ['cubone', 'marowak', 'marowak-alola'] },
    'soul-dew': { psychicBpMult: 1.2, dragonBpMult: 1.2, speciesRequirement: ['latias', 'latios'] },
    'lucky-punch': { criticalHitStageBoost: 2, speciesRequirement: 'chansey' },
    'leek': { criticalHitStageBoost: 2, speciesRequirement: ['farfetchd', 'farfetchd-galar', 'sirfetchd'] },
    'stick': { criticalHitStageBoost: 2, speciesRequirement: ['farfetchd', 'farfetchd-galar', 'sirfetchd'] },
    'metal-powder': { physicalDefenseMult: 2.0, speciesRequirement: 'ditto' },
    'quick-powder': { speedMult: 2.0, speciesRequirement: 'ditto' },

    // --- CONSUMABLES & STATE CHANGERS ---
    'white-herb': { restoresStatDrops: true, consumesOnUse: true },
    'mental-herb': { curesMentalVolatile: true, consumesOnUse: true },
    'power-herb': { skipsChargeTurn: true, consumesOnUse: true },
    'weakness-policy': { boostsAtkSpAtkOnSuperEffective: 2, consumesOnUse: true },
    'blunder-policy': { boostsSpeedOnMiss: 2, consumesOnUse: true },
    'room-service': { dropsSpeedInTrickRoom: 1, consumesOnUse: true },
    'eject-button': { forcesSwitchOnHit: true, consumesOnUse: true },
    'eject-pack': { forcesSwitchOnStatDrop: true, consumesOnUse: true },
    'red-card': { forcesOpponentSwitchOnHit: true, consumesOnUse: true },
    'throat-spray': { specialAttackBoostOnSoundMove: 1, consumesOnUse: true },
    'absorb-bulb': { specialAttackBoostOnWaterHit: 1, consumesOnUse: true },
    'cell-battery': { attackBoostOnElectricHit: 1, consumesOnUse: true },
    'luminous-moss': { specialDefenseBoostOnWaterHit: 1, consumesOnUse: true },
    'snowball': { attackBoostOnIceHit: 1, consumesOnUse: true },

    // --- WEATHER & TERRAIN EXTENDERS ---
    'damp-rock': { extendsWeather: 'rain', turns: 8 },
    'heat-rock': { extendsWeather: 'sun', turns: 8 },
    'smooth-rock': { extendsWeather: 'sand', turns: 8 },
    'icy-rock': { extendsWeather: 'snow', turns: 8 },
    'terrain-extender': { extendsTerrain: 'all', turns: 8 },

    // --- TYPE BOOSTING (1.2x) ---
    'silk-scarf': { typeOffenseMult: 'normal', bpMult: 1.2 },
    'charcoal': { typeOffenseMult: 'fire', bpMult: 1.2 },
    'mystic-water': { typeOffenseMult: 'water', bpMult: 1.2 },
    'magnet': { typeOffenseMult: 'electric', bpMult: 1.2 },
    'miracle-seed': { typeOffenseMult: 'grass', bpMult: 1.2 },
    'never-melt-ice': { typeOffenseMult: 'ice', bpMult: 1.2 },
    'black-belt': { typeOffenseMult: 'fighting', bpMult: 1.2 },
    'poison-barb': { typeOffenseMult: 'poison', bpMult: 1.2 },
    'soft-sand': { typeOffenseMult: 'ground', bpMult: 1.2 },
    'sharp-beak': { typeOffenseMult: 'flying', bpMult: 1.2 },
    'twisted-spoon': { typeOffenseMult: 'psychic', bpMult: 1.2 },
    'silver-powder': { typeOffenseMult: 'bug', bpMult: 1.2 },
    'hard-stone': { typeOffenseMult: 'rock', bpMult: 1.2 },
    'spell-tag': { typeOffenseMult: 'ghost', bpMult: 1.2 },
    'dragon-fang': { typeOffenseMult: 'dragon', bpMult: 1.2 },
    'black-glasses': { typeOffenseMult: 'dark', bpMult: 1.2 },
    'metal-coat': { typeOffenseMult: 'steel', bpMult: 1.2 },
    'fairy-feather': { typeOffenseMult: 'fairy', bpMult: 1.2 },

    // --- GENERAL DAMAGE & UTILITY BOOSTERS ---
    'expert-belt': { superEffectiveMult: 1.2 },
    'muscle-band': { physicalBpMult: 1.1 },
    'wise-glasses': { specialBpMult: 1.1 },
    'punching-glove': { punchingMoveMult: 1.1, makesMovesNonContact: true },
    'protective-pads': { makesMovesNonContact: true },
    'safety-goggles': { immuneToWeatherDamage: true, immuneToPowderMoves: true },
    'wide-lens': { accuracyMult: 1.1 },
    'zoom-lens': { accuracyMultIfMovingLast: 1.2 },
    'scope-lens': { criticalHitStageBoost: 1 },
    'razor-claw': { criticalHitStageBoost: 1 },

    // --- RESISTANCE BERRIES (Halve super-effective damage) ---
    'occa-berry': { reducesSuperEffectiveType: 'fire', damageReductionMult: 0.5, consumesOnUse: true },
    'passho-berry': { reducesSuperEffectiveType: 'water', damageReductionMult: 0.5, consumesOnUse: true },
    'wacan-berry': { reducesSuperEffectiveType: 'electric', damageReductionMult: 0.5, consumesOnUse: true },
    'rindo-berry': { reducesSuperEffectiveType: 'grass', damageReductionMult: 0.5, consumesOnUse: true },
    'yache-berry': { reducesSuperEffectiveType: 'ice', damageReductionMult: 0.5, consumesOnUse: true },
    'chople-berry': { reducesSuperEffectiveType: 'fighting', damageReductionMult: 0.5, consumesOnUse: true },
    'kebia-berry': { reducesSuperEffectiveType: 'poison', damageReductionMult: 0.5, consumesOnUse: true },
    'shuca-berry': { reducesSuperEffectiveType: 'ground', damageReductionMult: 0.5, consumesOnUse: true },
    'coba-berry': { reducesSuperEffectiveType: 'flying', damageReductionMult: 0.5, consumesOnUse: true },
    'payapa-berry': { reducesSuperEffectiveType: 'psychic', damageReductionMult: 0.5, consumesOnUse: true },
    'tanga-berry': { reducesSuperEffectiveType: 'bug', damageReductionMult: 0.5, consumesOnUse: true },
    'charti-berry': { reducesSuperEffectiveType: 'rock', damageReductionMult: 0.5, consumesOnUse: true },
    'kasib-berry': { reducesSuperEffectiveType: 'ghost', damageReductionMult: 0.5, consumesOnUse: true },
    'haban-berry': { reducesSuperEffectiveType: 'dragon', damageReductionMult: 0.5, consumesOnUse: true },
    'colbur-berry': { reducesSuperEffectiveType: 'dark', damageReductionMult: 0.5, consumesOnUse: true },
    'babiri-berry': { reducesSuperEffectiveType: 'steel', damageReductionMult: 0.5, consumesOnUse: true },
    'roseli-berry': { reducesSuperEffectiveType: 'fairy', damageReductionMult: 0.5, consumesOnUse: true },
    
    // --- STAT BERRIES & HEALING ---
    'sitrus-berry': { healsAtHpThreshold: 0.5, healFraction: 0.25, consumesOnUse: true },
    'liechi-berry': { physicalAttackBoostAtThreshold: 0.25, stageBoost: 1, consumesOnUse: true },
    'petaya-berry': { specialAttackBoostAtThreshold: 0.25, stageBoost: 1, consumesOnUse: true },
    'salac-berry': { speedBoostAtThreshold: 0.25, stageBoost: 1, consumesOnUse: true },
    'apicot-berry': { specialDefenseBoostAtThreshold: 0.25, stageBoost: 1, consumesOnUse: true },
    'ganlon-berry': { physicalDefenseBoostAtThreshold: 0.25, stageBoost: 1, consumesOnUse: true },
    'lansat-berry': { criticalHitBoostAtThreshold: 0.25, stageBoost: 2, consumesOnUse: true },
    'starf-berry': { randomStatBoostAtThreshold: 0.25, stageBoost: 2, consumesOnUse: true },
    'lum-berry': { curesStatus: 'all', consumesOnUse: true },
    
    // --- MEGA STONES ---
    'abomasite': { megaEvolves: 'abomasnow' },
    'absolite': { megaEvolves: 'absol' },
    'aerodactylite': { megaEvolves: 'aerodactyl' },
    'aggronite': { megaEvolves: 'aggron' },
    'alakazite': { megaEvolves: 'alakazam' },
    'altarianite': { megaEvolves: 'altaria' },
    'ampharosite': { megaEvolves: 'ampharos' },
    'audinite': { megaEvolves: 'audino' },
    'banettite': { megaEvolves: 'banette' },
    'beedrillite': { megaEvolves: 'beedrill' },
    'blastoisinite': { megaEvolves: 'blastoise' },
    'blazikenite': { megaEvolves: 'blaziken' },
    'cameruptite': { megaEvolves: 'camerupt' },
    'charizardite-x': { megaEvolves: 'charizard', megaForm: 'mega-x' },
    'charizardite-y': { megaEvolves: 'charizard', megaForm: 'mega-y' },
    'diancite': { megaEvolves: 'diancie' },
    'galladite': { megaEvolves: 'gallade' },
    'garchompite': { megaEvolves: 'garchomp' },
    'gardevoirite': { megaEvolves: 'gardevoir' },
    'gengarite': { megaEvolves: 'gengar' },
    'glalitite': { megaEvolves: 'glalie' },
    'gyaradosite': { megaEvolves: 'gyarados' },
    'heracrossite': { megaEvolves: 'heracross' },
    'houndoominite': { megaEvolves: 'houndoom' },
    'kangaskhanite': { megaEvolves: 'kangaskhan' },
    'latiasite': { megaEvolves: 'latias' },
    'latiosite': { megaEvolves: 'latios' },
    'lopunnite': { megaEvolves: 'lopunny' },
    'lucarionite': { megaEvolves: 'lucario' },
    'manectite': { megaEvolves: 'manectric' },
    'mawilite': { megaEvolves: 'mawile' },
    'medichamite': { megaEvolves: 'medicham' },
    'metagrossite': { megaEvolves: 'metagross' },
    'mewtwonite-x': { megaEvolves: 'mewtwo', megaForm: 'mega-x' },
    'mewtwonite-y': { megaEvolves: 'mewtwo', megaForm: 'mega-y' },
    'pidgeotite': { megaEvolves: 'pidgeot' },
    'pinsirite': { megaEvolves: 'pinsir' },
    'sablenite': { megaEvolves: 'sableye' },
    'salamencite': { megaEvolves: 'salamence' },
    'sceptilite': { megaEvolves: 'sceptile' },
    'scizorite': { megaEvolves: 'scizor' },
    'sharpedonite': { megaEvolves: 'sharpedo' },
    'slowbronite': { megaEvolves: 'slowbro' },
    'steelixite': { megaEvolves: 'steelix' },
    'swampertite': { megaEvolves: 'swampert' },
    'tyranitarite': { megaEvolves: 'tyranitar' },
    'venusaurite': { megaEvolves: 'venusaur' },
};
